

Ejercicio 1: Crear la libreria herramientas dentro de su carpeta de tareas, en su repositorio. Dentro deberán poner los métodos de Newton que construyeron, los métodos de integración, Euler independiente de dimensión (implícito y explícito)y Runge-Kutta independiente de dimensión. Recuerden que las rutinas deben funcionar solo con sus argumentos, no debe haber variables globales, todo lo que necesite la función para trabajar debe ser un argumento o una variable definida internamente.

* Las rutinas tienen que llevar su documentación.
* Crearán el notebook de la tarea 15 (para el Martes 17) y en el llamarán a su libreria con el comando import.
* Deberán demostrar que sus rutinas funcionan bien, no se necesitan tests extensos, basta con que muestren que si corren las rutinas.



In [26]:
__precompile__()

module milibreria


export Newt
function Newt(F,dF,x0,t) #En esta parte se calculan las raíces
    
    x=x0
        for i in 1:100 #Ciclo for en el que trabajará el programa
            x0=x0-(F(x0)/dF(x0)) #método de Newton
        end
    return x #Se obtiene la variable x
end

export Newt
function Newt(F,dF,I)    
    list1=zeros(length(I))                   
    x = 0                                           
    for i in 1:length(I)                    
        x = I[i]                            
        for n in 1:100                              
            x = x-(F(x)/dF(x))                      
            end                                     
    list1[i]=x                                     
    end
    list1                                            
end

#Metodos de integracion
export Riemann
function Riemann(f,a,b,subintervalos)         
    N = subintervalos                                 
    A = a
    B = b
    datos = []                                      
    suma = 0                                          
    area_bajo_la_curva = 0
    for i in 1:N                                       
        b = ((B-A)/N)*(i) - A                          
        a = A + ((B-A)/N)*(i-1)
        area_bajo_la_curva = (b-a)*(f((b+a)/2))        
        push!(datos,area_bajo_la_curva)              
    end
    suma = sum(datos,1:N)                             
return suma
end

export Trapecio
function Trapecio(f,a,b,subintervalos)            
    N = subintervalos                                  
    A = a
    B = b
    datos = []                                         
    suma = 0                                            
    area_bajo_la_curva = 0

    for i in 1:N
        b = ((B-A)/N)*(i) - A
        a = A + ((B-A)/N)*(i-1)
        area_bajo_la_curva = (b-a)*((f(b)+f(a))/2) 
        push!(datos,area_bajo_la_curva)
    end
    suma = sum(datos,1:N)
return suma
end


export Simpson


function Simpson(f,a,b,subintervalos)           
    N = subintervalos                                  
    A = a
    B = b
    datos = []                                         
    suma = 0                                           
    area_bajo_la_curva = 0

    for i in 1:N
        b = ((B-A)/N)*(i) - A
        a = A + ((B-A)/N)*(i-1)
        area_bajo_la_curva = (b-a)/6*((f(a)+4f((a+b)/2))+f(b))
        push!(datos,area_bajo_la_curva)
    end
    suma = sum(datos,1:N)
return suma
end


#Derivada

export derivada_numerica
function derivada_numerica(f,x,h)
    x0=x+h
    Num=f(x0)-f(x)
Der=Num/h
    return Der
end


export MetodoEuler
function MetodoEuler(f,x0,t0,tf,h) 
    n=round((tf-t0)/h)+1                 
    listt=linspace(t0,tf,n)             
    listx=zeros(n)         
    listx[1]=x0             
    for i in 1:length(listx)-1   
        listx[i+1]=listx[i]+h*f(listx[i],listt[i])
    end
    return listt, listx
end



export EulerImplicito
function EulerImplicito(f,x0,t0,tf,h)
  
       list1=t0:h:tf
    list2=[x0]
    for i in 1:length(list1)-1
        
    g(x,s)=x-h*f(x,list1[i])-x0 #Cálculo raíz
    x0=x0+h*f(Newt(g,Float64(x0),list1[i]),list1[i+1])
       
        push!(list2,x0)
    end
    return list1,list2
end

export EulerMedio
function EulerMedio(f,x0,t0,tf,h) #Método Euler Medio
    list1=t0:h:tf
    list2=[x0]
    for i in 1:length(list1)-1
        
    x0=x0+h*f(x0+(h*0.5)f(x0,list1[i]),list1[i]+h/2)
        
        push!(list2,x0)
    end
    return list1,list2
end


export RK
function RK(f,x0,t0,tf,h) #Runga Kutta simple
    list1=t0:h:tf
    list2=[x0]
    for i in 1:length(list1)-1
        
    k1=f(x0,list1[i])
    k2=f(x0+h*k1,list1[i]+h)   
    x0=x0+(h/2)*(k1+k2)
        
        push!(list2,x0)
    end
    return list1,list2
end


export RK4
function RK4(f,x0,t0,tf,h)
    list1=t0:h:tf
    list2=[x0]
    x=x0
    for i in 1:length(list1)-1
        
    k1=f(x,list1[i])#Se agregan las dos operaciones para cuarto orden
    k2=f(x+(h/2)*k1,list1[i]+h/2)  
    k3=f(x+(h/2)*k2,list1[i]+h/2) 
    k4=f(x+h*k3,list1[i]+h)
        
    x=x+(h/6)*(k1+2k2+2k3+k4)
        
        push!(list2,x)
    end
    return list1,list2
end
end

milibreria

In [3]:
import milibreria

In [4]:
milibreria.Newt(x->x^3-x^2-x-1,x->3x^2-2x-1,45,1)

45

In [27]:
milibreria.Riemann(x->x^3,0,1,1000)

1-element Array{Float64,1}:
 0.25

In [25]:
milibreria.Trapecio(x->x^3,0,1,1000)

1-element Array{Float64,1}:
 0.25

In [23]:
milibreria.Simpson(x->x^2,0,1,1000)

1-element Array{Float64,1}:
 0.333333

In [12]:
milibreria.derivada_numerica(x->x^2,1,100)

102.0

In [21]:
milibreria.MetodoEuler((x,t)->-(2.5)*x,1,0,8,0.5)

LoadError: InexactError()

In [16]:
milibreria.EulerMedio((x,t)->-(2.5)*x,1,0,8,0.5)

LoadError: InexactError()

In [17]:
milibreria.RK((x,t)->-(2.5)*x,1,0,8,0.5)

LoadError: InexactError()

In [19]:
milibreria.RK4((x,t)->[x[2], -1.0*x[1]-x[2]],0:0.01:10,[1,0])

LoadError: MethodError: no method matching RK4(::##33#34, ::FloatRange{Float64}, ::Array{Int64,1})
Closest candidates are:
  RK4(::Any, ::Any, ::Any, ::Any, ::Any) at In[2]:137